### ISSUE TITLE
Allow initialization without value or with null

### ISSUE THREAD

**Issue by chimon2000** [Flutterando/triple_pattern#49]
Triple currently does not allow nullable initial values.  When loading something from the server.  It feels like there is either a missing state AND/OR clients should be allowed to initialize with null.

Using a simple example where a client is loading a list of users, the triple would be [] -> loading -> [User()].  In this case we are saying that the initial state is a successful load of an empty array when it would be more accurate to say we haven't done anything yet.

1. Initialize the store in a pending/not asked state
2. Initialize the store with a nullable

**Comment by caioaao** [comment]
@Ascenio this violates the segmented state pattern though, right? You'd like to have the data state separated from the loading/error state. I think the problem is not the state representation, but how the library implements the loading state. Something like [react-query](https://react-query.tanstack.com/) seems more useful here, in which instead of having `loading` be a simple boolean, it'd be one of three states: `NotLoaded`, `Loading` and `Loaded`. Notice that this is completely independent of what the initial state might be and the benefits can be seen on the react-query project, but the TLDR is that clients have a lot more flexibility to use the available data or loading state as they see fit.

**Comment by jacobaraujo7** [comment]
Issue closed, but any other issue we can reopen it.
